spring.application.name=management-app

# --- Database Configuration ---
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=160723@rd

spring.datasource.driver-class-name=org.postgresql.Driver
# --- JPA / Hibernate Settings ---
# 'update' will automatically create/update tables in your DB based on your Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Server Port ---
server.port=8080

# --- JWT Secret (Keep this secure) ---
# Ensure this matches the secret length required by your JwtUtils class
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# --- File Upload Limits (Optional but good for bug prevention) ---
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB